import Head from 'next/head'
import s from '../styles/pages/404.module.scss'

export default function NotFound() {
  return (
    <div>
      <Head>
        <title>Not found | 404</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={s.not_found}>
        <div className={s.not_found__wrapper}>
          <h1>Not found</h1>
        </div>  
      </div>
    </div>
  )
}
