import Head from 'next/head'
import {GetStaticProps} from "next";
import Container from '../components/Container'
import Layout from '../components/Layout'
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import s from '../styles/pages/404.module.scss'
import { useTranslation } from 'next-i18next';

export default function NotFound() {

  const { t } = useTranslation()

  const translates = {
    title: t('coop:title__404'),
  }
  return (
    <Layout>
      <Head>
        <title>{translates.title} | ™SHE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <div className={s.not_found}>
          <div className={s.not_found__wrapper}>
            <h1>{translates.title}</h1>
          </div>  
        </div>
      </Container>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async ({locale}) => {
  return {
    props:{
      ...(await serverSideTranslations(locale as string ?? 'ru', ['coop', 'common']))
    },
    revalidate: 10
  }
}
