import Head from 'next/head'
import {GetStaticProps} from "next";
import Container from '../components/Container'
import Layout from '../layout/layout'
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import s from '../styles/pages/404.module.scss'
import { useTranslation } from 'next-i18next';

export const getStaticProps: GetStaticProps = async ({locale}) => {
  return {
    props:{
      ...(await serverSideTranslations(locale as string, ['coop', 'common', 'footer']))
    },
    revalidate: 10
  }
}

export default function NotFound() {

  const { t } = useTranslation()

  const translates = {
    title: t('coop:title__404'),
    clear: t('fav:clear'),
    empty: t('fav:empty'),
    toCatalogue: t('fav:toCatalogue'),
    footer: {
      titles: {
        profile: t('footer:profile'),
        info: t('footer:info'),
        contacts: t('footer:contacts'),
        video: t('footer:video'),
      },
      links: {
        profile_link1: t('footer:profile_link1'),
        profile_link2: t('footer:profile_link2'),
        profile_link3: t('footer:profile_link3'),
        profile_link4: t('footer:profile_link4'),
        info_link1: t('footer:info_link1'),
        info_link2: t('footer:info_link2'),
        info_link3: t('footer:info_link3'),
        info_link4: t('footer:info_link4'),
        info_link5: t('footer:info_link5'),
        contacts_link1: t('footer:contacts_link1'),
        contacts_link2: t('footer:contacts_link2'),
        contacts_link3: t('footer:contacts_link3'),
        video_link1: t('footer:video_link1'),
        video_link2: t('footer:video_link2'),
        video_link3: t('footer:video_link3'),
        video_link4: t('footer:video_link4'),
      },
    },
  }
  return (
    <Layout links={translates.footer.links} titles={translates.footer.titles}>
      <Head>
        <title>{translates.title} | ™SHE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <div className={s.not_found}>
          <div className={s.not_found__wrapper}>
            <h1>{translates.title}</h1>
          </div>  
        </div>
      </Container>
    </Layout>
  )
}
