import Head from 'next/head'
import {GetStaticProps} from "next";
import Container from '../components/Container'
import Layout from '../components/Layout'
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import s from '../styles/pages/404.module.scss'
import { useTranslation } from 'next-i18next';
import React from "react";

export default function Error() {

  const { t } = useTranslation('common')

  return (
    <Layout>
      <Head>
        <title>{`${t('error_page.title')} | ™SHE`.replace('<!-\- -->','')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <div className={s.not_found}>
          <div className={s.not_found__wrapper}>
            <h1>{t('error_page.title')}</h1>
            <p>{t('error_page.paragraph')}</p>
          </div>
        </div>
      </Container>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async ({locale}) => {
  return {
    props:{
      ...(await serverSideTranslations(locale as string ?? 'ru', ['coop', 'common']))
    },
    revalidate: 10
  }
}
